### ISSUE TITLE
Lookup values

### ISSUE THREAD

**Issue by tucotuco** [inbo/whip#11]
Similar to Issue #9 in nature, suppose you wanted to provide a vocabulary resolution through lookup feature? For example, for every three letter country code, lookup and use the 2-letter equivalent.

**Comment by peterdesmet** [comment]
whip doesn't do any data transformation (e.g. from 3 to 2 letter codes), so I'm not sur I'm following your example: can you elaborate?

**Comment by tucotuco** [comment]
Ah, right. I keep projecting Kurator onto it. :-)

**Comment by peterdesmet** [comment]
😊
