### ISSUE TITLE
Negative values not covered with current syntax on `numberformat`

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/whip#17]
Currently, we have no information or guidelines about negative values for the numberformat.  Options are:

- users need to be explicit about negative values: mixed negative and non-negative values in a single columns is probably 
- we just look at the absolute value of the incoming number (ignoring - sign)

**Comment by peterdesmet** [comment]
I would do the latter, and ignore minus sign of values. Negative values are more important in min/max

**Comment by stijnvanhoey** [comment]
fixed by #19
