### ISSUE TITLE
redundant evaluation test `equals`

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/whip#2]
As the test `equals` can be expressed by a combination of the terms `min` and `max`, this evaluation test is rather redundant. 

e.g. 
```
equals: 10
```
is equal to this test description:
```
min: 10
max: 10
```

This is similar for the `length` test (combination of `minlength` and `maxlength`.

It could be considered useful to keep this as a separate test out of convenience for the user. Still, when `equals` is considered, one could argue to include `equalsdate` and `equalslength` as well. 

Therefore, I would leave `equals` out as a separate test option.

**Comment by peterdesmet** [comment]
Agreed. Also, by removing it, it cannot create confusion with `allowed`.

**Comment by stijnvanhoey** [comment]
done!
